### ISSUE TITLE
bugs.racket-lang.org is down

### ISSUE THREAD

**Issue by jameshfisher** [racket/racket-lang-org#102]
```
$ curl bugs.racket-lang.org
curl: (7) Failed to connect to bugs.racket-lang.org port 80: Operation timed out
$ curl https://bugs.racket-lang.org
curl: (7) Failed to connect to bugs.racket-lang.org port 443: Operation timed out
```

**Comment by spdegabrielle** [comment]
this has been replaced by GitHub issues.
Please close

**Comment by samth** [comment]
We still need to bring back the content of this site, although not the bug reporting facility.

**Comment by spdegabrielle** [comment]
Even if the database still usable I'm concerned resource/motivation to do this piece of work is not realistically available in the core team.

Would you be willing to dump the DB file on GitHub and we can see if we can find a volunteer to do the data migration?  (Was it GNATS?)

**Comment by samth** [comment]
The database is now at https://github.com/racket/gnats-bugs

**Comment by spdegabrielle** [comment]
Thanks @samth 
@jameshfisher Please close if this is now resolved.

**Comment by sorawee** [comment]
As mentioned above, bugs.racket-lang.org is now replaced with GitHub issues, and the content of the site is archived at https://github.com/racket/gnats-bugs. Closing.
