### ISSUE TITLE
Home page says Racket is an LGPL project

### ISSUE THREAD

**Issue by zyrolasting** [racket/racket-lang-org#115]
https://github.com/racket/racket-lang-org/blob/b2d3bc56b618562a11273ae4f3bbbecc3ccd80f4/www/index.html.pm#L52

**Comment by sorawee** [comment]
Fixed. I think this can be closed.

**Comment by zyrolasting** [comment]
Thanks much

**Comment by sorawee** [comment]
Oh, @kryptine was the one who fixed it. Sorry if my above comment misled you.
