### ISSUE TITLE
`announce` mailing list offline

### ISSUE THREAD

**Issue by spdegabrielle** [racket/racket-lang-org#116]
Hi, 
The `announce` list on mailman and gmane mirror are both offline, with 'list not found' and 'Error 522'(timeout) respectively. 

NB the archive is still active, but the last archived announcement was the 7.2 release.

KR

Stephen

**Comment by spdegabrielle** [comment]
if announce is removed we can probably close #11

**Comment by samth** [comment]
The plan is for it to return.
