### ISSUE TITLE
Arrows on Start Quickly examples incorrctly placed on phone.

### ISSUE THREAD

**Issue by LeifAndersen** [racket/racket-lang-org#12]
When viewing the website from a phone, the arrows for Start Quickly appear over text rather than off to the side.
![screenshot_20160108-114021](https://cloud.githubusercontent.com/assets/285926/12207470/be7e569c-b614-11e5-9503-b32112024718.png)

**Comment by rfindler** [comment]
The advice I got about this is to turn the phone horizontally.

**Comment by shriram** [comment]
When [an] owner of a Usonian house telephoned [Frank Lloyd] Wright in desperation because the rain was pouring in through a leak in the roof, the master calmly suggested: “Why don't you move your chair a little bit to one side?”
—Peter Blake, _The Master Builders_

**Comment by LeifAndersen** [comment]
Yup, when I rotate the arrows do go to the right place. I take it that it's not an easy fix then to move them further to the right when the screen width is too small?

**Comment by rfindler** [comment]
@LeifAndersen give it a try! I have no clue and would welcome a less Wrightian fix :)

**Comment by samth** [comment]
I've tried hard to come up with something that works well here, and the current state is as good as I could get it. But I'm sure something better could be done.

**Comment by LeifAndersen** [comment]
Okay, I've submitted a PR that I 'think' fixes it, although I've only really tested it in firefox.

**Comment by mbutterick** [comment]
Closed as obsolete.
