### ISSUE TITLE
Buggy download page

### ISSUE THREAD

**Issue by sorawee** [racket/racket-lang-org#120]
1. Navigate to https://download.racket-lang.org/racket-minimal-v7.6.html. Notice that there are two "Variant" select widgets. Only the second one is functional.
2. Click the "Platform" select widget. There are duplicate choices. E.g., `Windows (x64, 64-bit)` appears twice. I believe this over-counting happens because there are two suffixes for Windows: `tgz` and `exe`. Though I think it makes more sense to show these variants in the "Variant" select widgets (and in fact it already does this).
3. Choose `Windows (x64, 64-bit)`. There are four variants: `Regular`, `Regular`, `CS`, and `CS`. Again, this happens because for each variant, there are two suffixes. It would be nice to display `Regular (tgz)`, `Regular (exe)`, `CS (tgz)`, `CS (exe)` instead.

**Comment by jbclements** [comment]
This is probably my fault, and almost certainly my responsibility, regardless of whether it's my fault.
