### ISSUE TITLE
the link to htdp on https://www.htdp.org triggers a certificate warning on chrome and safari

### ISSUE THREAD

**Issue by spdegabrielle** [racket/racket-lang-org#125]
This occurs for https://www.htdp.org not https://htdp.org 
(image below)

Possible actions;

- [x] change links at racket-lang.org from https://www.htdp.org to https://htdp.org (short term)

- [x] redirect www.htdp.org to htdp.org at dns level (I think this is possible but I may be wrong)

![image](https://user-images.githubusercontent.com/108047/83748402-09ce3d80-a65a-11ea-9d15-3d7d05774fc6.png)

**Comment by spdegabrielle** [comment]
created #126 as short term fix.  
(does not resolve issue for links elsewhere)

**Comment by samth** [comment]
From the DNS results, this looks like something that @shriram needs to fix, since currently www.htdp.org points to shriram.github.io. Or maybe that's the wrong DNS entry.

**Comment by shriram** [comment]
@mflatt and I just made some DNS updates. Please keep an eye out — hopefully you'll see it changed within the next 24 hours.

**Comment by spdegabrielle** [comment]
fixed. Thank you @samth @shriram and @mflatt
