### ISSUE TITLE
'IDE Support' mentions arrows but screenshot does not show arrows

### ISSUE THREAD

**Issue by spdegabrielle** [racket/racket-lang-org#137]
Should have a screenshot or GIF that shows arrows

![arrows](https://user-images.githubusercontent.com/108047/90989854-9969f500-e594-11ea-985f-52012e3edee0.png)

Annoyingly the default mac screenshot tool can't capture the '3 bound occurrences':
![image](https://user-images.githubusercontent.com/108047/90989939-26ad4980-e595-11ea-82cb-ed9e04dab9d4.png)

Embedded gif or video may be better: [video showing arrows](https://youtu.be/CSXmqtSpYTo)

screen recording tools that have successfully been used https://github.com/racket/racket/wiki/screen-recording

**Comment by rfindler** [comment]
screen recording seems like a neat idea. [Here's a poorly executed version.](https://users.cs.northwestern.edu/~robby/tmp/example-movie.gif) We would want one that has more of a plan, uses the source code from the repo, moves perhaps a bit more slowly so people can see what's going on and covers a few more features.

Maybe if someone finds time to make such a thing we can drop it in where the current image is?

**Comment by mfelleisen** [comment]
Lovin' it. @spdegabrielle @rfindler

**Comment by spdegabrielle** [comment]
https://www.cockos.com/licecap/ was used by @sorawee to record the gif's for https://github.com/sorawee/fishy-completion 
https://github.com/NickeManarin/ScreenToGif is used by @alex-hhh 
Both give very good results.
Other options listed at https://github.com/racket/racket/wiki/screen-recording

**Comment by spdegabrielle** [comment]
I think the brief example showing renaming and arrows was good.

**Comment by sorawee** [comment]
Fixed by aa543634575eb9ece55c640cdb4d5346e59baa55
