### ISSUE TITLE
update lists page to provide mailing-list only link for users 

### ISSUE THREAD

**Issue by spdegabrielle** [racket/racket-lang-org#139]
mailing-list only link
https://groups.google.com/forum/#!forum/racket-users/join

It is undesirable for some users to have/use a google account for accessing racket-users

is this the correct file?
https://github.com/racket/racket-lang-org/blob/master/lists/index.rkt

**Comment by spdegabrielle** [comment]
Note: I have updated links on reddit /r/racket and Racket discord 
**Ways to get help**
* documentation https://docs.racket-lang.org  (searchable)
* mailing list, Racket Slack, IRC
* Searching the mailing list https://groups.google.com/g/racket-users

Ask questions at 
a) the Racket Slack: Signup first: https://racket-slack.herokuapp.com/  -  https://racket.slack.com/
b) the mailing list: https://groups.google.com/forum/#!forum/racket-users/join  (no google ID required)
 c) Google Group: https://groups.google.com/forum/#!forum/racket-users/ (same content as mailing-list)

**Comment by mflatt** [comment]
I think this is covered by other issues and changes, but please re-open if I misunderstand.
