### ISSUE TITLE
Broken links on https://racket-lang.org/community.html

### ISSUE THREAD

**Issue by spdegabrielle** [racket/racket-lang-org#143]
Broken links on https://racket-lang.org/community.html
This page may be an orphan, I think I got to it from the mailing list archive.

**Comment by Bost** [comment]
Also, under the https://racket-lang.org/books.html the link (https://www.springer.com/de/book/9783835101555) to the book:

>     Die Macht der Abstraktion
>     Einführung in die Programmierung.

is not working.

**Comment by mfelleisen** [comment]
Thanks. I pushed a revised link to the DMdA book at Springer’s site.

**Comment by mflatt** [comment]
The URL that used to have an orphaned page now redirects to the front page.
