### ISSUE TITLE
Is https://racket-lang.org on the racket web server?

### ISSUE THREAD

**Issue by spdegabrielle** [racket/racket-lang-org#149]
wondering if some aspects of the website could be automated?
- database/API backed things including, but not limited to the donors page.
- perhaps include a 'racket playground' based on RacketScript sometime in the future.

Would this offer opportunities? - or is the cost too high?

**Comment by samth** [comment]
racket-lang.org is a static site hosted on AWS S3. I think a database for holding information doesn't add much over a static file, which can be generated with Racket code. 

For a playground, that should be a separate site, and would want to be a real web server. But pasterack.org and https://try-racket.defn.io/ already exist and work well.

**Comment by spdegabrielle** [comment]
thank you
