### ISSUE TITLE
IRC page appears to be blank.

### ISSUE THREAD

**Issue by LeifAndersen** [racket/racket-lang-org#15]
When I go to the IRC page:

https://racket-lang.org/irc-chat.html

I get a white page with the navbar at the top. Can anyone else confirm this?

**Comment by jbclements** [comment]
> On Feb 10, 2016, at 6:16 PM, Leif Andersen <notifications@github.com> wrote:
> 
> When I go to the IRC page:
> 
> https://racket-lang.org/irc-chat.html
> 
> I get a white page with the navbar at the top. Can anyone else confirm this?

Yes, but firefox shows an icon indicating that it has blocked non-secure parts of the page. In the interest of science, I temporarily disabled the protection, and saw a page asking me to log in to IRC. So, I suspect this is related to our new cert, and also to Firefox.

John

**Comment by samth** [comment]
This just needs a change to reference the irc iframe with HTTPS in the source.

**Comment by mbutterick** [comment]
Appears to be working normally; closed as obsolete
