### ISSUE TITLE
Racket users `join` link requires a google account.

### ISSUE THREAD

**Issue by spdegabrielle** [racket/racket-lang-org#154]
I don't know how much of a problem, but a racketeer on reddit/r/racket reported that the join link was requiring a google account.  It is my understanding that this is a problem for some people.

the link https://groups.google.com/forum/#!forum/racket-users/join  - previously this didn't require a google account.

I believe sending an email to racket-users+subscribe@googlegroups.com should work to subscribe. 
(Use racket-users+unsubscribe@googlegroups.com to unsubscribe)

**Comment by spdegabrielle** [comment]
I'm sorry I don't have time to action this myself.

**Comment by spdegabrielle** [comment]
https://www.reddit.com/r/Racket/comments/leoq92/is_usersracketlangorg_still_operational/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

**Comment by spdegabrielle** [comment]
Subsequent dialog 

- how to subscribe/unsubscribe by email not documented 
- somehow the user was provided a different address for posting to the list (perhaps from gg subscription confirmation?)

**Comment by spdegabrielle** [comment]
Plan:

1. Test & Document on a wiki page 
2. Create pr for https://lists.racket-lang.org/ to make this easier for new subscribers

**Comment by spdegabrielle** [comment]
- [ ] Create wiki page
- [ ] Test subscribe by link (is gg account required?)
- [ ] Test subscribe by email
- [ ] Check subscription confirmation emails? 
- [ ] repeat for announce & dev
- [ ] Check archive links on https://lists.racket-lang.org/

**Comment by spdegabrielle** [comment]
* Sending an email to racket-users+subscribe@googlegroups.com should work to subscribe does not require a google account. 
  * you must **reply** to the email to join without using or creating a google account.

**Comment by mflatt** [comment]
This is now mostly covered, except for the part about replying to actually join. Should we add that caveat to the page, or is the message that Google sends clear enough?

**Comment by spdegabrielle** [comment]
i think it is fine
