### ISSUE TITLE
IRC link is broken

### ISSUE THREAD

**Issue by rmculpepper** [racket/racket-lang-org#155]
The "#racket IRC" link under the Community tab now goes to a generic "we have been acquired" page.

**Comment by mfelleisen** [comment]
What’s the correct link?

**Comment by rmculpepper** [comment]
IIUC, the link used to go to a page that provided a log of the `#racket` channel on freenode.org. The channel still seems to exist, but the log service seems to have been discontinued. I don't know of a replacement, but I don't know the IRC ecosystem.

**Comment by samth** [comment]
I think we should switch the link to https://webchat.freenode.net/#racket

There's no more active logging for the IRC channel.

**Comment by tonyg** [comment]
See also #159 which inter alia removes references to botbot.me
