### ISSUE TITLE
Add link to Racket Discord(chat) 

### ISSUE THREAD

**Issue by spdegabrielle** [racket/racket-lang-org#156]
Racket discord invite link https://discord.gg/6Zq8sH5

I’ll do this myself - this issue is a reminder for me to do the PR

**Comment by spdegabrielle** [comment]
Add this near line 445

```
◊link["https://discord.gg/6Zq8sH5"]{Racket Discord} (chat)
```

**Comment by mfelleisen** [comment]
I have added the line. It'll go public with the release of 8.1 in a week or two.
