### ISSUE TITLE
Exxon foundation link returns page not found

### ISSUE THREAD

**Issue by spdegabrielle** [racket/racket-lang-org#176]
Exxon foundation link returns page not found

**Comment by sorawee** [comment]
In 2018, that link (http://www.exxonmobil.com/Corporate/community_foundation.aspx) redirects to https://corporate.exxonmobil.com/en/community/worldwide-giving/exxonmobil-foundation, which in turn is redirected to https://corporate.exxonmobil.com/en/community/worldwide-giving/exxonmobil-foundation/overview (all links are now dead) 

Judging from how it used to look from https://web.archive.org/web/20181003042702/https://corporate.exxonmobil.com/en/community/worldwide-giving/exxonmobil-foundation/overview (ExxonMobil Foundation overview), relevant pages that currently are not dead would be:

- https://corporate.exxonmobil.com/news/reporting-and-publications/sustainability-report/social/social-contributions-and-philanthropy#Education (Philanthropy and social contributions > Education)
- https://corporate.exxonmobil.com/news/reporting-and-publications/sustainability-report/social/social-contributions-and-philanthropy/stem-education/ (STEM education)
- https://corporate.exxonmobil.com/news/reporting-and-publications/sustainability-report/social/social-contributions-and-philanthropy/stem-education/united-states-education-initiatives (United States education initiatives)
- https://corporate.exxonmobil.com/news/reporting-and-publications/sustainability-report/social/social-contributions-and-philanthropy/stem-education/our-partners-in-supporting-education-worldwide (Our partners in supporting education worldwide)

Perhaps @mfelleisen can tell what a good replacement link is.

**Comment by mfelleisen** [comment]
Thanks @sorawee for doing my homework research.

**Comment by mfelleisen** [comment]
Pushed.
