### ISSUE TITLE
Robby Findler old link

### ISSUE THREAD

**Issue by SimonLSchlee** [racket/racket-lang-org#196]
https://racket-lang.org/team.html > Project management > [Robby Findler](https://www.eecs.northwestern.edu/~robby/)
leads to a "Page Not Found" page
Probably it should also use the link that is used at the top in the "Recognized Contributors" section?
That uses [Robby Findler](https://www.cs.northwestern.edu/~robby/)

**Comment by rfindler** [comment]
Thank you; the change is to the more appropriate link, but the "eecs" one does indeed work for me. Does it still fail for you?

**Comment by SimonLSchlee** [comment]
When I inspect it with Firefox:
GET | https://www.eecs.northwestern.edu/~robby/
gives me a: 301 Moved Permanently
response header:
Location | https://www.mccormick.northwestern.edu/electrical-computer/~robby/

and that is then a 404 Page not Found

**Comment by rfindler** [comment]
Oh, thank you! I had incorrectly tried the `http` version. I'll let the people maintaining the website know.
