### ISSUE TITLE
replace heroku invite service with slack invite link

### ISSUE THREAD

**Issue by spdegabrielle** [racket/racket-lang-org#223]
Just found out that free accounts on Heroku are being discontinued:  https://blog.heroku.com/next-chapter
I note that the self registration for [racket.slack.com](http://racket.slack.com/) is at https://racket-slack.herokuapp.com/
....and it is offline currently.

An Invite link is available to administrators of the racket slack, and works for 400 signups. (thanks Jens)

Instructions here: 
https://slack.com/intl/en-gb/help/articles/201330256-Invite-new-members-to-your-workspace#share-an-invitation-link

I do not have permissions to create an invite link. 

If an admin provides a link I am happy to make the PR

https://github.com/racket/racket-lang-org/blob/8c1072853af9fd57629c8841c2fa09555d93fee8/www/index.html.pm#L438

**Comment by sorawee** [comment]
Fixed by #224
