### ISSUE TITLE
Version-Specific Documentation URLs Broken

### ISSUE THREAD

**Issue by dergemkr** [racket/racket-lang-org#226]
In the Scribble [documentation](https://docs.racket-lang.org/scribble/running.html#%28part._xref-flags%29), it mentions to link to `http://download.racket-lang.org/docs/$version$/html/` for more stable URLs than http://docs.racket-lang.org/, but it all of these URLs (e.g. [8.6](https://download.racket-lang.org/docs/8.6/html/)) are returning a 404.

**Comment by mflatt** [comment]
Thanks for the report! I've pushed an updated to the Scribble documentation, which will take effect at  http://docs.racket-lang.org/ on the next release.
