### ISSUE TITLE
Link to realm of racket site on books page broken

### ISSUE THREAD

**Issue by spdegabrielle** [racket/racket-lang-org#227]
https://www.realmofracket.com/

my browser is reporting it cannot connect to the server

https://github.com/racket/racket-lang-org/blob/2b43da3b6b2fc35959eb475e571994a743af6ec7/www/books.html.pm#L16

**Comment by spdegabrielle** [comment]
Nb I have emailed the author @mfelleisen

**Comment by mfelleisen** [comment]
I am checking into this. (I am not really the web master for this project.)

**Comment by stchang** [comment]
Hi we're aware of the issue and looking into it. Thanks

**Comment by stchang** [comment]
We're back. Thanks for the notification
