### ISSUE TITLE
Add contact info for specific people to `friendly.html.pm`

### ISSUE THREAD

**Issue by LiberalArtist** [racket/racket-lang-org#233]
I was reminded today that @samth [had sugested](https://twitter.com/samth/status/1586876473478193153) (in response to @LeifAndersen) a change to: https://github.com/racket/racket-lang-org/blob/f2f3e3bd3872f137affa1b117abaa20d808e1262/www/friendly.html.pm#L14

> &hellip; I agree that providing specific contact information for some individual people in addition to a broad group would be valuable, particularly in cases where there's an issue involving a member of that group. I'll look into adding that.

I don't feel like the right person to draft that change, but I also think it would be valuable: I'm opening this issue so we don't forget about it.

**Comment by mflatt** [comment]
Closing as done.
