### ISSUE TITLE
blog: rss/atom return content type octet-stream

### ISSUE THREAD

**Issue by avelino** [racket/racket-lang-org#235]
because returning the content type as `octet-stream`?

```
curl -I -H "Content-Type: application/octet-stream" -X GET https://blog.racket-lang.org/feeds/all.atom.xml
HTTP/2 200 
date: Thu, 15 Dec 2022 10:15:49 GMT
content-type: application/octet-stream
```

it has blocked the use of rss readers

**Comment by avelino** [comment]
@soegaard @jeapostrophe this update should have solved it?

**Comment by samth** [comment]
The update needs to be deployed first, I will do that soon.

**Comment by avelino** [comment]
@samth the site has not been deployed yet, can you tell when it will be deployed?

**Comment by ndaidong** [comment]
@avelino n the meantime, you can use my proxy (quite slow):

https://webfeed.deta.dev/api/xmlify?url=https://blog.racket-lang.org/feeds/all.atom.xml

**Comment by avelino** [comment]
worked with data.dev, I set the [clj.social](https://clj.social/) bot to read the racket blog feed and publish here, sharing the blog content on fediverse (mastodon)
https://clj.social/@racketlang

**Comment by jessealama** [comment]
Still returning `application/octet-stream`.

**Comment by mflatt** [comment]
This is now fixed (via a change to `s3-sync`).
