### ISSUE TITLE
delete the logo bar on docs.racket-lang.org

### ISSUE THREAD

**Issue by mbutterick** [racket/racket-lang-org#27]
Rather than change this to match the new logo, I would prefer to delete it (though I’m not sure where in this repo it’s controlled, or if it's elsewhere.)

No reasonable human will be confused by the loss of this ’90s wayfinding artifact. See, e.g., [the Rust docs](https://doc.rust-lang.org/book/getting-started.html).

**Comment by stamourv** [comment]
I agree.
One thing I do like about the bar, though, (which probably doesn't apply to the Rust docs) is that it makes it immediately obvious that one is looking at the online version of the docs, rather than a local one. Probably not indispensable, though.

**Comment by mfelleisen** [comment]
I will miss it and the shield. :((((

**Comment by mbutterick** [comment]
I would be open to the idea of amending the CSS for the docs themselves to behave differently when they're displayed on racket-lang.org (e.g., put a small logo & link to the main home page), so there’s a visual distinction from local builds.

But the current header strip would still need to be clipped off (it is being added to the docs from outside)

**Comment by stamourv** [comment]
Sounds like a good solution to me.

**Comment by mbutterick** [comment]
How is the toolbar prepended to the docs pages? Does it have something to do with [this file?](https://github.com/racket/racket-lang-org/blob/master/stubs/docs.rkt) Obviously I don’t want to just take a machete to things. (Actually, that’s not true. I do. But prudence stays my hand.)

Once that’s removed, I will do a PR for `racket/scribble` that updates the CSS for the docs.

**Comment by mflatt** [comment]
Building the web pages creates "stubs/docs", or something like that, containing "doc-site.css" and "doc-site.js". Those two files get uploaded to docs.racket-lang.org manually.

To test out a change, you can copy those two files to the directory of a local build (to replace the stub files there).

**Comment by mbutterick** [comment]
Aha, so that’s what those two files do. OK, maybe I can just do it all the surgery as one PR here.

**Comment by mbutterick** [comment]
http://docs.racket-lang.org/guide/index.html

I prefer how this looks. Any dissenters?

In Mac OS Chrome I see a little flash on each page when the logo loads (I didn’t see this on my local test) though not in Safari or Firefox, so maybe it’s just a me glitch, not a world glitch.

**Comment by rfindler** [comment]
It looks great on my browser, but strange on my phone. (image attached; ios safari, latest version as far as I know)

![img_3957](https://cloud.githubusercontent.com/assets/399024/21535706/4bd3c82e-cd3e-11e6-9f1d-9b79dc07534c.PNG)

**Comment by mbutterick** [comment]
You're seeing a cached copy @rfindler. The white header bar is now gone and the logo appears opposite the search box.

Also, I made a [separate fix](https://github.com/racket/scribble/commit/37019a1eb69e9a9268e1ae9a891b9b7bfe4f5f49) in `racket/scribble` to force the one-column layout on phones. But I don’t know when that will propagate to the `docs` server.

**Comment by rfindler** [comment]
Looks like my problem was caching too. Never mind.
