### ISSUE TITLE
update individuals.html.pm list 

### ISSUE THREAD

**Issue by spdegabrielle** [racket/racket-lang-org#289]
this list of individuals listed at 

https://racket-lang.org/individuals.html

Has not been updated for while. 

I'm happy to update the list by contacting new donors to ask if they consent, and doing a PR to update the page source

https://github.com/racket/racket-lang-org/blob/master/www/individuals.html.pm

**Comment by sorawee** [comment]
@rfindler @jbclements would it make sense, as a part of the release process, to also update this donor list? (I choose the release process because it's a reoccurring event, but doing it every X months would be reasonable as well.)

I guess a part of this would involve asking SFC for the list, and someone (@spdegabrielle?) could then update the page from that information.

**Comment by jbclements** [comment]
I’d certainly be happy to add a “send email to Stephen” item to the checklist. I think once every 12 months would probably be plenty? AFAICT, this does not need to be synchronized with the release, it’s just asking Stephen to make a pull request against the website.

John

**Comment by spdegabrielle** [comment]
Since logging this I’ve looked into this more closely and discovered that both SFC and GitHub seek permission before publishing donor names
https://sfconservancy.org/sustainer/
https://github.com/sponsors/racket/

The process last time(Aug 2020) was to email donors and ask permission - but this became a guessing game because contact details are not available.

I will repeat the process - please send the list of SFC donors (privately) and I’ll contact the new ones and seek their permission to be listed and finalise a PR in a few weeks so as many as possible can respond.

I don’t agree with yearly updates - it should be immediate and we should send a thank you note and a laptop sticker - but yearly is a step in the right direction.

S.

**Comment by sorawee** [comment]
I generally agree with @spdegabrielle that frequent updates don't hurt (well, it's a work for people who need to handle this, which as I understand will be @spdegabrielle and SFC). But infrequent updates (which is where we are right now) could hurt. "Immediate" might be overkill though.

> thank you note and a laptop sticker

In my opinion, I would avoid this, or at the very least not make it a requirement. For one, there will be a shipping cost and the sticker also has cost. If I donate $1, my intention is to add the funds, not add $1 and subtract $x where x > 1.

**Comment by spdegabrielle** [comment]
> > thank you note and a laptop sticker
> 
> In my opinion, I would avoid this, or at the very least not make it a requirement. For one, there will be a shipping cost and the sticker also has cost. If I donate $1, my intention is to add the funds, not add $1 and subtract $x where x > 1.

It could be optional like FSF https://my.fsf.org/join?mtm_campaign=fall23&mtm_source=modal

My idea is the sticker may occasionally start a conversation.

**Comment by sorawee** [comment]
@spdegabrielle are you working on this?

**Comment by spdegabrielle** [comment]
My current thoughts are updating individuals in the current mechanism is unsustainable.
I'll do a PR to point to the supported on GitHub ( where they have consented to be publicised)
and do a general thank you to those who contribute via SFC - but apologies we can't currently thank them by name as there is no consent mechanism

**Comment by spdegabrielle** [comment]
changed my mind and decided to delete the out-of-date page, and just linked to list of supporters who gave consent via GitHub.
#299

**Comment by LiberalArtist** [comment]
Do you think the current list includes individuals who have not given consent to be acknowledged?
