### ISSUE TITLE
Feedback from HN

### ISSUE THREAD

**Issue by aminb** [racket/racket-lang-org#31]
Congrats for the new design, looks great @mbutterick!

The website was [posted to HN](https://news.ycombinator.com/item?id=13242590) today, and there's some fair points raised (e.g. some concerns with the hoverable cards) about the new design. I thought I'd let you guys know if you want to look into them.

**Comment by roman-neuhauser** [comment]
As an on-and-of beginner in racket, I'm not too happy.  Everything I need from the home page is hidden, either behind opaque graphics, or below the fold.

**Comment by mbutterick** [comment]
Thank you, noted.
