### ISSUE TITLE
Windows download link just links to https://download.racket-lang.org/

### ISSUE THREAD

**Issue by AviDeGabrielle** [racket/racket-lang-org#322]
![image](https://github.com/user-attachments/assets/1f12b841-2a34-4f30-b250-0fd5e42d8f3d)
Windows download button links to https://download.racket-lang.org/

**Comment by AviDeGabrielle** [comment]
@spdegabrielle

**Comment by sorawee** [comment]
Thanks for the report. That was my bad. Fixing soon...

**Comment by sorawee** [comment]
Fixed. Thanks again for the report!
