### ISSUE TITLE
S3 sync not working correctly

### ISSUE THREAD

**Issue by mbutterick** [racket/racket-lang-org#35]
The upload after fix #32 [didn’t work correctly](https://github.com/racket/racket-lang-org/pull/32#issuecomment-269517362) — the refreshed `index.html` was uploaded but not the accompanying `styles.css`. I can’t tell if it failed to upload at all, or if there’s some cache holding onto the old version.

On the homepage now, you can see the problem in the code boxes — the font size is too large and doesn’t fit in the box.

**Comment by mbutterick** [comment]
FWIW the sync after PR #33 didn’t work correctly either. As with #32, the updated `css/styles.css` is generated correctly, but apparently is not uploaded.

**Comment by mflatt** [comment]
Sorry that I missed this before. I the problem is most likely caching at the CloudFlare level.

Probably we should change the build of the web pages to create a unique name for each version of the ".css" file to avoid caching problems.

**Comment by stamourv** [comment]
As I mentioned on #32, I did try purging the cloudflare cache for `css/styles.css`, but no luck.

**Comment by mbutterick** [comment]
I think I figured it out. According to the [CloudFlare docs](https://support.cloudflare.com/hc/en-us/articles/200168256-What-are-CloudFlare-s-caching-levels-), appending a query string will force a cache refresh of a non-HTML file. So we don’t have to change the filename of the CSS every time (which would be a bad policy) but rather just append a fresh query string to the URL used within the HTML (which is easy). Hold on and I will push a test for this theory.

**Comment by mbutterick** [comment]
I'm appending a timestamp to the CSS &JS query strings to induce Cloudflare to serve fresh copies. Let me know if that runs afoul of the policy in favor of deterministic compilation. If so I will change it to rely on a manually updated version number, which will have the same effect (if my theory is correct).

**Comment by mflatt** [comment]
I think we do want it to be more deterministic. How about using a hash of the file content?

**Comment by mbutterick** [comment]
Fair enough. How about PR #38: I send the content of each source file through `sha1` and append that as the query string for the respective URL.

**Comment by samth** [comment]
Doesn't this defeat the caching entirely? What about using that as part of the URL?

**Comment by mflatt** [comment]
@samth: It shouldn't. We use the "Standard" caching level at CloudFlare, which treats the query like part of the path for caching.

**Comment by mbutterick** [comment]
AFAIK browsers do the right thing — e.g., in Chrome do `chrome://cache/` in the address bar and it will show you its cache database, which will include lots of URLs with query strings.

**Comment by mflatt** [comment]
The SHA1 hash looks like the right change to me
