### ISSUE TITLE
Add link to slack

### ISSUE THREAD

**Issue by samth** [racket/racket-lang-org#42]
There should be a link to the Racket slack. Should it link to https://racket.slack.com or to http://racket-slack.herokuapp.com/ ?

**Comment by stamourv** [comment]
Ideally, we'd link to the latter, and the latter would have a link to the former.

**Comment by samth** [comment]
I think that's already the case

**Comment by stamourv** [comment]
If so, I can't find the link.
Maybe it links once you ask for an invite, but that's no use for someone who's already registered.

**Comment by bennn** [comment]
Closing, since the slack channel & signup link are currently on the main page
