### ISSUE TITLE
is https://docs.racket-lang.org updated separately from the http version?

### ISSUE THREAD

**Issue by mbutterick** [racket/racket-lang-org#44]
I notice that the https://docs.racket-lang.org site still has the old navbar.

**Comment by samth** [comment]
This looks fixed to me. Can you confirm, @mbutterick?

**Comment by lexi-lambda** [comment]
I get inconsistent behavior. At home, I see the old navbar. At work, I see the new design. Is it possible that some CloudFront edge servers didn’t get properly purged while others did?

**Comment by mbutterick** [comment]
I still see the old navbar with `https`. Meanwhile, with `http`, I still get the old `doc-site.js`.

I guess this is all entangled with the cache-invalidation issues explored in issue #35.

In general I don’t love the fact that we’re having to stick a bunch of nonsense into our codebase to empty these caches. 

More broadly, this S3 / Cloudflare system feels like using an elephant to squash a peanut. I love Racket, but traffic-wise we’re not exactly BuzzFeed. Why is this system necessary? For instance, I can (and do) serve [hundreds of simultaneous users](http://practicaltypography.com/the-scorpion-express.html#the-file-size-myth) on my LAMP droplet at DO for $6 a month. 

The problem is that we are incurring the headaches of a massive caching system without the benefits. Right now, there are glitches happening for some subset of R website users that we don’t know about (and can’t test for, and that aren’t reproducible). (See also: the problems with RSS feeds in PR #26, which could be easily fixed with an `.htaccess`.) 

This isn’t an aimless gripe — we depend on the website, and we like to commit frequently, but the website infrastructure is oriented toward a different goal.

**Comment by samth** [comment]
I get identical versions on both `http` and `https` (I checked the contents of `doc-site.js` and it's the same on both). 

Our experience is that hosting our static pages on static site hosting (such as S3) is both cheaper and more reliable than hosting them on dynamic sites that we manage. Also, the S3 system has been quite easy to manage.

Cloudflare makes it possible to run this system with https, sensible caching, and easy-to-manage DNS.

**Comment by rfindler** [comment]
Except that maybe not "sensible" caching?

**Comment by mbutterick** [comment]
Hey, as long as no one complains when nasty hacks like PR #38 start to show up in `racket/scribble` or the docs in order to trick S3 / Cloudflare into doing the right thing. :scream: *Amazon made me do it ...*

**Comment by mbutterick** [comment]
PS how about considering the [“basic” caching level](https://support.cloudflare.com/hc/en-us/articles/200168256-What-are-CloudFlare-s-caching-levels-) rather than the current “aggressive”, which at least gives us more control over when cached resources are used.

**Comment by samth** [comment]
As a first step, I just purged the entire CloudFlare cache, so we can see if that fixes things (which would point at the cache as the problem).

**Comment by mbutterick** [comment]
> Our experience is that hosting our static pages on static site hosting (such as S3) is both cheaper and more reliable than hosting them on dynamic sites that we manage. Also, the S3 system has been quite easy to manage.

PS Is there a (good) reason we avoid using the Racket web server?

**Comment by samth** [comment]
For the dynamic sites (such as the dynamic parts of pkgs.racket-lang.org) we do.

**Comment by mbutterick** [comment]
> I just purged the entire CloudFlare cache, so we can see if that fixes things (which would point at the cache as the problem).

After I clear my local caches, this is what I see in Mac OS Chrome, Safari, and Firefox:

![screen shot 2017-01-25 at jan 25 10 16 48 am](https://cloud.githubusercontent.com/assets/1425051/22303279/6ded296e-e2e7-11e6-9270-0967657b7512.gif)

**Comment by samth** [comment]
I now see that as well, but since 6.8 was just released and I didn't see that an hour ago, I suspect a new issue.

@stamourv ?

**Comment by stamourv** [comment]
The docs page still says 6.7, so the release probably didn't change anything.
FWIW, I did remove the part of the release process that was adding the banner.

**Comment by mbutterick** [comment]
I am no longer seeing the old banner — AFAICT the problem is cured. @samth, perhaps you could note what steps you took on the server side to purge the caches, so that future generations can learn from your wisdom.

**Comment by samth** [comment]
I went to the CloudFlare dashboard, clicked on the Caching tab, and then clicked the drop-down for "Purge Everything".

**Comment by mbutterick** [comment]
Is there a way to put this operation into our standard S3 sync script?
