### ISSUE TITLE
How does the docs subdomain relate to the pkgs subdomain?

### ISSUE THREAD

**Issue by WildYorkies** [racket/racket-lang-org#47]
Does https://docs.racket-lang.org/ contain docs for the best/official packages? 

When you install a package, does that also install the package's documentation so `raco docs` can access it?

Just trying to get a sense for how the Racket ecosystem works outside of the core distribution.

**Comment by mbutterick** [comment]
`docs.racket-lang.org` has 1) all the documentation for Racket’s core libraries and 2) the docs for every package listed on `pkgs.racket-lang.org` that has documentation.

Yes, when you install a package locally, the docs for that package are also installed locally.
