### ISSUE TITLE
https://htdp.org points to http://pyret.org

### ISSUE THREAD

**Issue by evelynmitchell** [racket/racket-lang-org#49]
This looks to be a web server configuration issue.
A secure request or htdp.org goes to http://pyret.org.
http://www.htdp.org resolves correctly.
https://pyret.org resolves to http://pyret.org

128.148.32.110 is Brown University Computer Science, so they'll have to help fix this.

dig htdp.org

; <<>> DiG 9.10.3-P4-Ubuntu <<>> htdp.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 42518
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;htdp.org.                      IN      A

;; ANSWER SECTION:
htdp.org.               3599    IN      A       128.148.32.110

;; Query time: 62 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Thu Feb 09 18:06:15 MST 2017
;; MSG SIZE  rcvd: 53

https://www.pyret.org/ has a valid cert.
dig pyret.org

; <<>> DiG 9.10.3-P4-Ubuntu <<>> pyret.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 5043
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;pyret.org.                     IN      A

;; ANSWER SECTION:
pyret.org.              10799   IN      A       217.70.184.38

;; Query time: 184 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Thu Feb 09 18:07:35 MST 2017
;; MSG SIZE  rcvd: 54

**Comment by samth** [comment]
Note that instead of just going to pyret.org, https://htdp.org produces a certificate error currently.

**Comment by LiberalArtist** [comment]
This issue appears to have been resolved.
