### ISSUE TITLE
Links are not obvious in introduction

### ISSUE THREAD

**Issue by philnguyen** [racket/racket-lang-org#5]
In the introduction text `Racket is a full-spectrum ... GUI and charts`, there are lots of links that appear as normal text (e.g. `objects`, `types`, `laziness`, `GUI`, `charts`, etc.). I wouldn't have realized they were links to other pages had I not accidentally hovered the mouse over them. As the links from other parts of the page do stand out, I guess this is not intended.

**Comment by leafac** [comment]
With the deployment of the new Racket website, this issue can be closed.
