### ISSUE TITLE
No (OK, very hidden) explanation of "Minimal Racket vs Racket"

### ISSUE THREAD

**Issue by dvanhorn** [racket/racket-lang-org#67]
On the [download page](https://download.racket-lang.org/), there is an option to download Racket or Minimal Racket, but there's no explanation of what "Minimal Racket" means.  Of the first set of links there: Announcement, Notes, Documentation, More Variants and Checksums, none have any explanation.  Searching the documentation for "Minimal" turns up nothing.

You have to go to "Snapshot Builds", Utah or Northwestern, then click "?" on Minimal Racket to find out what it means: "Includes just enough of Racket that you can use raco pkg to install more."  Then you'd have to navigate back (unless you actually want a snapshot) to the download page.

Seems like there really ought to be a description on the download page.  There probably ought to be the same description on the "More Variants" page as the "Snapshot" page (they have a very similar structure), too.

**Comment by jackfirth** [comment]
Should a description of this go in the Racket documentation or the racket-lang.org website?

I lean towards adding an "Installing Racket" section of the documentation that describes minimal vs. full racket and other related stuff, like how to use the linux installer script and how to install racket from sources other than `download.racket-lang.org`, such as with Homebrew or `apt-get`.

**Comment by samth** [comment]
I think that section of the documentation would be good, but also that what @dvanhorn suggests is also needed.

**Comment by ICEYSELF** [comment]
Now is 9102. I googled for the "Minimal racket" explanation and found this page. I think an directly accessible explaination on the download page is necessary.

**Comment by EmmanuelOga** [comment]
I was confused too. Found this page through same search as ICEYSELF 😃
