### ISSUE TITLE
Link to Racket Manifesto is dead

### ISSUE THREAD

**Issue by codingbum** [racket/racket-lang-org#68]
https://www.ccis.northeastern.edu/home/matthias/manifesto/

Error 404.

The new url? http://felleisen.org/matthias/manifesto/

**Comment by mfelleisen** [comment]
I’d rather not (though it was an accident that the Manifesto got removed). 

[[ I suspect my CCIS web page will completely disappear soon. ]]

**Comment by rfindler** [comment]
Google currently points to your old webpages with the first hit on "racket manifesto" (despite the fact that it is a broken line). I believe that if you put a redirect in then that will change.

**Comment by rfindler** [comment]
Wait, I'm confused. It isn't a broken link anymore.

**Comment by mfelleisen** [comment]
I checked my directory. The full path is there, the index file is there, I have no clue why this fails. My best guess is that CCIS’s recent re-organization is the actual problem. So there’s now a second reason for migrating everything to felleisen.org <http://felleisen.org/>.
