### ISSUE TITLE
gmane mirror It's not working

### ISSUE THREAD

**Issue by avelino** [racket/racket-lang-org#76]
All link (mirror) on gmane It's not working, should we remove it?

ex on page https://lists.racket-lang.org/ :
- http://news.gmane.org/gmane.comp.lang.racket.devel
- http://blog.gmane.org/gmane.comp.lang.racket.devel
- nntp://news.gmane.org/gmane.comp.lang.racket.devel
- http://rss.gmane.org/messages/complete/gmane.comp.lang.racket.devel
- http://rss.gmane.org/topics/complete/gmane.comp.lang.racket.devel

http://dir.gmane.org/gmane.comp.lang.racket.devel all links internal page gmane stop working

That may be the reason: http://home.gmane.org/2016/09/06/reboot-v1/

**Comment by mflatt** [comment]
Updated the page (finally!) to remove gmake links.
