### ISSUE TITLE
Not all subdomains redirect http to https 

### ISSUE THREAD

**Issue by LiberalArtist** [racket/racket-lang-org#79]
All of the [racket-lang.org](http://racket-lang.org) subdomains support https. Some of them, like [download.racket-lang.org](http://download.racket-lang.org) (maybe a particularly security-conscious one?), redirect http to https. 

Others, however, do not: in particular, the main [racket-lang.org](http://racket-lang.org) domain and [docs.racket-lang.org](http://docs.racket-lang.org) do not redirect to https.

**Comment by spdegabrielle** [comment]
I believe this is now fixed. 

If you are happy please close.

Kind regards, 

Stephen

**Comment by sorawee** [comment]
This appears to be fixed. Closing.
