### ISSUE TITLE
`slides` subdirectory not copied to public website

### ISSUE THREAD

**Issue by mbutterick** [racket/racket-lang-org#81]
@jeapostrophe is troubled.

**Comment by mbutterick** [comment]
The site-publishing function `copy-annual-site!` copies subdirectories on an opt-in basis. Meaning: it assumes subdirs want to be tracked in the source tree (and thus not listed in `.gitignore`) but not published to the public website. 

With this patch, any subdirectories named `fonts` or `slides` will be copied as well.

If it seems a little tortured to list the publishable project subdirectories in a source file outside of those projects, I agree. But the whole `plt-web` mechanism is slightly tortured. In the end I found it easier to play by its rules than fight.

**Comment by jeapostrophe** [comment]
Thanks! I see now why it was hard to do :)
